export const DICT = {
    READ_MORE: "Read More",
    LOGIN: "Login",
    LOGOUT: "Logout",
    REGISTER: "Register",
    NO_ACCOUNT_MESSAGE: "Don't you have an account?",
    HAVE_ACCOUNT_MESSAGE: "Do you have an account?",
    UPLOAD_IMAGE: "Upload Image",
    PUBLISH: "Publish",
    STATUS: "Status:",
    DRAFT: "Draft",
    PUBLIC: "Public",
    VISIBILITY: "Visibility:",
    SAVE_DRAFT: "Save as a draft",
    CATEGORY: "Category",
    ART: "Art",
    SCIENCE: "Science",
    TECHNOLOGY: "Technology",
    CINEMA: "Cinema",
    DESIGN: "Design",
    FOOD: "Food",
    FOOTER_FIRST: "Made with ♥️ and ",
    FOOTER_SECOND: "React.js",
    MENU_TITLE: "Other posts you may like",
    WRITE: "Write",
}